### ISSUE TITLE
本项目的服务器需要在海外吗？

### ISSUE THREAD

**Issue by aslan9** [key7men/openai-feishu-bot#1]

**Comment by forkpath** [comment]
有两种方式：
1. 服务器在国内，那么需要在服务器上配置代理，譬如使用CentOS作为服务器，那么可以配置一个Clash客户端，并且选择非大陆或香港的节点来访问OpenAI提供的API
2. 服务器在海外，那么需要保证在没有梯子的情况下，可以正常访问该服务器

我最开始部署的时候，方式是1，但VPN经常要切换节点，比较麻烦，所以目前我正在使用的方式是后者，截止到回答这个issue的时候已经运行了15d，一切正常。

海外节点，国内的云服务厂商都有，可以自行选择。
